from pathlib import Path
data_folder = Path("data/raw")
files = sorted(data_folder.glob("*.nc"))
print()
print("========================================")
print("NOAA NETCDF FILE CHECK")
print("========================================")
print()
print("Data folder:", data_folder.resolve())
print()
print("Number of .nc files found:", len(files))
print()
print("========== FILES ==========")
for i, file in enumerate(files, start=1):
    print(f"{i}. {file.name}")
print()
print("========================================")
print("CHECK COMPLETE")
print("========================================")